LPS-94654 export-import-test: Create ExportImportMultiLanguageSearchTest
foshiro/liferay-portal pull request #8
Opened 2019-06-24 15:26 UTC by brandizzi

2019-06-24 15:26 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2019-06-24 20:18 UTC, foshiro commented
ci:test:sf

2019-06-24 20:18 UTC, foshiro commented
ci:test:search

2019-06-24 20:18 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-8.liferay.com/job/test-portal-source-format/1215/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-8.liferay.com//userContent/jobs/test-portal-source-format/builds/1215/jenkins-report.html">here</a>.</b></p>

2019-06-24 20:19 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest(master)/4554/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-14.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4554/jenkins-report.html">here</a>.</b></p>

2019-06-24 20:21 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 2 minutes 26 seconds 51 ms</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/a1a9991d0176fde3a426dc16b40ef2d15960bf76">a1a9991d0176fde3a426dc16b40ef2d15960bf76</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/brandizzi/liferay-portal/tree/pr-704">pr-704</a><br/>Branch GIT ID: <a href="https://github.com/brandizzi/liferay-portal/commit/79c7cbe9cb46f28a3319617203c49a5866430616">79c7cbe9cb46f28a3319617203c49a5866430616</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-8.liferay.com/job/test-portal-source-format/1215/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-8.liferay.com/userContent/jobs/test-portal-source-format/builds/1215/jenkins-report.html">here</a>.</h5></details></html>

2019-06-24 21:47 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:search - 16 out of 19 jobs passed in 1 hour 28 minutes 7 seconds 218 ms</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/12edc9582da2005d7d3209d6a1eaa7fefdd61a3d">12edc9582da2005d7d3209d6a1eaa7fefdd61a3d</a></p><h4>Copied in Private Modules Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal-ee/tree/master-private">master-private</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal-ee/commit/6fcc4852b869c7f10650f51b86a5a80992540d75">6fcc4852b869c7f10650f51b86a5a80992540d75</a></p>16 out of 19 jobs PASSED<div><h4>3 Failed Jobs:</h4><ul><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest(master)/4554/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/212160/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/central-requirements-jdk8</strong></strike></a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/278639/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8</strong></strike></a></li></ul></div><details><summary><strong>16 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/296848/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/172149/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</a></li><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/212161/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/10</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/278638/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/2</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/257916/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/3</a></li><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/212159/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/4</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/278637/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/5</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/278636/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/6</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/296846/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/7</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/296845/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/8</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/278635/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/9</a></li><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/212158/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/257917/">test-portal-acceptance-pullrequest-batch(master)/modules-semantic-versioning-jdk8</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/296844/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/257918/">test-portal-acceptance-pullrequest-batch(master)/semantic-versioning-jdk8</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/296847/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8</a></li></ul></details><h5>For more details click <a href="https://test-1-14.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4554/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/212160/">test-portal-acceptance-pullrequest-batch(master)/central-requirements-jdk8</a></h5><div><h6>Job Results:</h6><p>6 Tests Passed.<br/>1 Test Failed.</p></div><ol><li><div><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/212160//consoleText">AXIS_VARIABLE=0,label_exp=!master #212160</a><ol><li><div><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/212160//testReport/com.liferay.portal.modules/ModulesStructureTest/testScanBuildScripts">ModulesStructureTest.testScanBuildScripts</a><pre><code>junit.framework.AssertionFailedError: Version must match the project version (2.0.0) modules/apps/frontend-js/frontend-js-react-web/package.json
	at com.liferay.portal.modules.ModulesStructureTest._testJSONVersion(ModulesStructureTest.java:1400)
	at com.liferay.portal.modules.ModulesStructureTest.access$500(ModulesStructureTest.java:66)
	at com.liferay.portal.modules.ModulesStructureTest$1.preVisitDirectory(ModulesStructureTest.java:244)
	at com.liferay.portal.modules.ModulesStructureTest$1.preVisitDirectory(ModulesStructureTest.java:122)
	at java.nio.file.Files.walkFileTree(Files.java:2677)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at com.liferay.portal.modules.ModulesStructureTest.testScanBuildScripts(ModulesStructureTest.java:120)
</code></pre></div></li></ol></div></li></ol></div></li><li><div><h5><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/278639/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8</a></h5><div><h6>Job Results:</h6><p>8 Tests Passed.<br/>2 Tests Failed.</p></div><ol><li><div><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=1,label_exp=!master/278639//consoleText">AXIS_VARIABLE=1,label_exp=!master #278639</a><pre><code>     [exec] * What went wrong:
     [exec] Execution failed for task ':apps:export-import:export-import-test:compileTestIntegrationJava'.
     [exec] &gt; Compilation failed; see the compiler error output for details.
     [exec] 
     [exec] * Try:
     [exec] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':apps:export-import:export-import-test:compileTestIntegrationJava'.
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
     [exec] 	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
     [exec] 	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
     [exec] 	at org.gradle.api.in [...]

2019-06-25 13:05 UTC, foshiro-zz requested changes
@vagner-castro Code and tests looks good to me. Just have to change PermissionCheckerTestRule to PermissionCheckerMethodTestRule

2019-06-25 13:05 UTC, foshiro-zz commented on modules/apps/export-import/export-import-test/src/testIntegration/java/com/liferay/exportimport/internal/search/test/ExportImportMultiLanguageSearchTest.java
> +import com.liferay.portal.test.rule.PermissionCheckerTestRule;
Please, change to PermissionCheckerMethodTestRule

2019-06-25 13:05 UTC, foshiro-zz commented on modules/apps/export-import/export-import-test/src/testIntegration/java/com/liferay/exportimport/internal/search/test/ExportImportMultiLanguageSearchTest.java
> +			PermissionCheckerTestRule.INSTANCE,
Please, change to PermissionCheckerMethodTestRule

2019-06-25 13:39 UTC, vagnerbc commented
@foshiro Chages updated

2019-06-25 13:41 UTC, foshiro commented
ci:test:sf

2019-06-25 13:42 UTC, foshiro commented
ci:test:search

2019-06-25 13:42 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest(master)/4293/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-16.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4293/jenkins-report.html">here</a>.</b></p>

2019-06-25 13:42 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-22.liferay.com/job/test-portal-source-format/2647/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-22.liferay.com//userContent/jobs/test-portal-source-format/builds/2647/jenkins-report.html">here</a>.</b></p>

2019-06-25 13:45 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes 14 seconds 712 ms</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/a1a9991d0176fde3a426dc16b40ef2d15960bf76">a1a9991d0176fde3a426dc16b40ef2d15960bf76</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/brandizzi/liferay-portal/tree/pr-704">pr-704</a><br/>Branch GIT ID: <a href="https://github.com/brandizzi/liferay-portal/commit/49def3cede603e0b9db7dbb45ae9e6cea1b233af">49def3cede603e0b9db7dbb45ae9e6cea1b233af</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-22.liferay.com/job/test-portal-source-format/2647/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-22.liferay.com/userContent/jobs/test-portal-source-format/builds/2647/jenkins-report.html">here</a>.</h5></details></html>

2019-06-25 14:59 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:search - 18 out of 21 jobs passed in 1 hour 17 minutes 16 seconds 727 ms</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/17ec6f9f5d0dd3078cf49d2a2d3185c4c148ecf5">17ec6f9f5d0dd3078cf49d2a2d3185c4c148ecf5</a></p><h4>Copied in Private Modules Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal-ee/tree/master-private">master-private</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal-ee/commit/50ef18f65f57ecd996cff7f07a4f128213bac2eb">50ef18f65f57ecd996cff7f07a4f128213bac2eb</a></p>18 out of 21 jobs PASSED<div><h4>3 Failed Jobs:</h4><ul><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest(master)/4293/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/297064/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</strong></strike></a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/302822/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8</strong></strike></a></li></ul></div><details><summary><strong>18 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/251315/">test-portal-acceptance-pullrequest-batch(master)/central-requirements-jdk8</a></li><li><a href="https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/172955/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/297065/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/10</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/262638/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/11</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/302821/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/12</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/300931/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/2</a></li><li><a href="https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/172954/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/3</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/302820/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/4</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/297062/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/5</a></li><li><a href="https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/172953/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/6</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/300930/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/7</a></li><li><a href="https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/172952/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/8</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/297060/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/9</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/297061/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/300932/">test-portal-acceptance-pullrequest-batch(master)/modules-semantic-versioning-jdk8</a></li><li><a href="https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/172951/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/300933/">test-portal-acceptance-pullrequest-batch(master)/semantic-versioning-jdk8</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/297063/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8</a></li></ul></details><h5>For more details click <a href="https://test-1-16.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4293/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/297064/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</a></h5><div><h6>Job Results:</h6><p>20 Tests Passed.<br/>1 Test Failed.</p></div><ol><li><div><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=1,label_exp=!master/297064//consoleText">AXIS_VARIABLE=1,label_exp=!master #297064</a><ol><li><div><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=1,label_exp=!master/297064//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_Search_SearchDifferentScopesViaNewSite_">LocalFile.Search#SearchDifferentScopesViaNewSite</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-16/1561470152555/test-portal-acceptance-pullrequest(master)/4293/functional-tomcat90-mysql57-jdk8/1/1/LocalFile.Search_SearchDifferentScopesViaNewSite/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-16/1561470152555/test-portal-acceptance-pullrequest(master)/4293/functional-tomcat90-mysql57-jdk8/1/1/LocalFile.Search_SearchDifferentScopesViaNewSite/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-16/1561470152555/test-portal-acceptance-pullrequest(master)/4293/functional-tomcat90-mysql57-jdk8/1/1/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li></ol></div></li></ol><hr/><details><summary><strong>Failures in common with <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream(master)">acceptance upstream results</a> at 17ec6f9f5d0dd3078cf49d2a2d3185c4c148ecf5:</strong></summary><ol><li><div><h5><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/302822/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8</a></h5><div><h6>Job Results:</h6><p>1403 Tests Passed.<br/>1 Test Failed.</p></div><ol><li><div><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=3,label_exp=!master/302822//consoleText">AXIS_VARIABLE=3,label_exp=!master #302822</a><ol><li><div><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=3,label_exp=!master/302822//testReport/com.liferay.module.configuration.localization.test/ModuleConfigurationLocalizationTest/testConfigurationLocalization">ModuleConfigurationLocalizationTest.testConfigurationLocalization</a><pre><code>java.lang.AssertionError: Test failed due to: 
Bundle {id: 320, name: com.liferay.segments.asah.connector, version: 2.0.0}
	Configuration {pid:c [...]

2019-06-25 16:07 UTC, foshiro-zz approved these changes

2019-06-25 16:22 UTC, foshiro commented
Submitted https://github.com/brandizzi/liferay-portal/pull/779

2019-06-25 16:22 UTC, closed without merging